Welcome to Scrabble!
-------------------
Menu
----
1. New Game
2. Load Game
3. Credits (Show student information)
4. Quit
5. DEBUG: Player + Hand Test

> 
--------------------------------------
Name: Syed Ali
Student ID: s3736294
Email: s3736294@student.rmit.edu.au

Name: Mitchell Reid
Student ID: s3901557
Email: s3901557@student.rmit.edu.au

Name: Tsz Him Matthew Cheung
Student ID: s3902085
Email: s3902085@student.rmit.edu.au

Name: Spencer Morrison
Student ID: s3906025
Email: s3906025@student.rmit.edu.au
--------------------------------------
Menu
----
1. New Game
2. Load Game
3. Credits (Show student information)
4. Quit
5. DEBUG: Player + Hand Test

> Goodbye!
