Welcome to Scrabble!
-------------------
Menu
----
1. New Game
2. Load Game
3. Credits (Show student information)
4. Quit
5. DEBUG: Player + Hand Test

> 
Enter the filename from which load a game
> 
KOALA, it's your turn
Score for POTATO: 0
Score for KOALA: 0
    1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
  -------------------------------------------------------------
A | A | B | B |   |   |   |   |   |   |   |   |   |   |   |   |
B |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
C |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
D |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
E |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
F |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
G |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
H |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
I |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
J |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
K |   |   |   | E |   |   |   |   |   |   |   |   |   |   |   |
L |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
M |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
N |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
O |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |

Your hand is
B-3, A-1, N-1, R-1, A-1, V-4, E-1

> > > > > > 
POTATO, it's your turn
Score for POTATO: 0
Score for KOALA: 14
    1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
  -------------------------------------------------------------
A | A | B | B | B | N | A | R | A |   |   |   |   |   |   |   |
B |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
C |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
D |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
E |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
F |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
G |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
H |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
I |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
J |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
K |   |   |   | E |   |   |   |   |   |   |   |   |   |   |   |
L |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
M |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
N |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
O |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |

Your hand is
E-1, Q-10, P-3, B-3, Z-10, O-1, S-1

> > 
KOALA, it's your turn
Score for POTATO: 2
Score for KOALA: 14
    1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
  -------------------------------------------------------------
A | A | B | B | B | N | A | R | A |   |   |   |   |   |   |   |
B | E |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
C |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
D |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
E |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
F |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
G |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
H |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
I |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
J |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
K |   |   |   | E |   |   |   |   |   |   |   |   |   |   |   |
L |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
M |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
N |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
O |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |

Your hand is
V-4, E-1, S-1

> > > > Game over
Score for POTATO: 2
Score for KOALA: 36
Player KOALA won!
Menu
----
1. New Game
2. Load Game
3. Credits (Show student information)
4. Quit
5. DEBUG: Player + Hand Test

> Goodbye!
